### ISSUE TITLE
Clean UP & Dockerization eos69p9

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos69p9#2]

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
Since rdkit 2020.9.1 and rdkit 2022.9.5 have the same descriptors in the same order, `RUN conda install -c conda-forge rdkit=2020.09.1` was changed to `RUN pip install rdkit==2022.9.5`
[rdkit_2020_09_1_descriptors.csv](https://github.com/ersilia-os/eos69p9/files/12073155/rdkit_2020_09_1_descriptors.csv)
[rdkit_2022_09_5_descriptors.csv](https://github.com/ersilia-os/eos69p9/files/12073156/rdkit_2022_09_5_descriptors.csv)
Also, Deep Graph Library; dgl is now installed using pip instead of conda.

The model works well locally.
Input file: [eml_canonical.csv](https://github.com/ersilia-os/eos69p9/files/12073370/eml_canonical.csv)

**Run.sh**: This accepts files with only one column(also no header needed)
Output: [run_output.csv](https://github.com/ersilia-os/eos69p9/files/12075726/run_output.csv)

**CLI`**: 👍 Model eos69p9 fetched successfully!, [eos69p9_fetch_updated_repo.log](https://github.com/ersilia-os/eos69p9/files/12073380/eos69p9_fetch_updated_repo.log)
CLI Output: [eml_69p9_cli_output.csv](https://github.com/ersilia-os/eos69p9/files/12073407/eml_69p9_cli_output.csv)
```
🚀 Serving model eos69p9: ssl-gcn-tox21

   URL: http://127.0.0.1:41301
   PID: 20451
   SRV: conda

👉 To run model:
   - run

💁 Information:
   - info
(ersilia) hellenah@hellenah-elitebook:~$ ersilia run -i "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1"
{
    "input": {
        "key": "MCGSCOLBFJQGHM-SCZZXKLOSA-N",
        "input": "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1",
        "text": "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1"
    },
    "output": {
        "outcomes": [
            0.2414434850215912,
            0.04542943462729454,
            0.08307256549596786,
            0.07301757484674454,
            0.016418687999248505,
            0.15253399312496185,
            0.07397028058767319,
            0.04572156444191933,
            0.019902464002370834,
            0.03363495692610741,
            0.035861220210790634,
            0.03406665101647377
        ]
    }
}
```

This and other changes to file and folder structure/organization are reflected in the [PR](https://github.com/ersilia-os/eos69p9/pull/3)
